### ISSUE TITLE
dir organisation

### ISSUE THREAD

**Issue by ghost** [PurLinux/Kernel#1]
i'd recommend that we cut some of the structure out.

(version)/binary:
git doesn't do well with binary files, so i'd recommend we not store binary blobs. did you plan on storing the compiled kernel here?

(version)/source:
this will always be available via kernel.org (the creators of git itself!). i recommend instead if you wish to have the source available as part of this repository, we implement it via a single git submodule (since it's tagged for each release, this means we won't need to contain multiple trees of source either).

**Comment by RainbowHackerHorse** [comment]
Yeah, agreed. Wasn't thinking when I mentioned those. MAKE IT SO CAPTAIN.
Except for Source. I want to be mirroring the latest Tarball. There's a mad reason in my crazy ol noggin.

**Comment by ghost** [comment]
per SMS and recreating here for tracking, tarballs will be mirrored via infra

**Comment by ghost** [comment]
done. also added submodule for upstream sources. you can find into on how to use it in README, but tl;dr:

pull/clone the repo, then:

git submodule init
git submodule update
